### ISSUE TITLE
Topology

### ISSUE THREAD

**Issue by martin9115** [ncd-io/ncd-red-wireless#10]
Hi. As far as i know, NCD use Xbee with DigiMesh, but can we somehow visualize the connections (topology) between the sensor nodes (to see how the sensors send data between themselves)?

**Comment by zaphod-42** [comment]
Not using this library. Topology can be determined using the Digi API commands, or using software from digi... I haven't tested this yet, but the [XBEE Network Assistant](https://www.digi.com/support/productdetail?pid=5642&type=utilities) looks like it may work.
