### ISSUE TITLE
Support on Wireless Vibration Sensor

### ISSUE THREAD

**Issue by davidfungf** [ncd-io/ncd-red-wireless#6]
When the code is tested on wireless vibration sensor, the data x / y / z value cannot be decoded. Can you add the sensor type 40 in your library? Thanks.

{ "topic": "sensor_data", "payload": { "nodeId": 0, "firmware": 4, "battery": 3.2940600000000004, "counter": 1, "sensor_type": 40, "sensor_data": { "type": "unknown", "data": [ 0, 11, 210, 0, 20, 204, 0, 11, 167, 0, 41, 238, 0, 51, 78, 0, 47, 186, 255, 188, 76, 255, 196, 87, 255, 204, 221, 0, 23 ] }, "type": "sensor_data", "addr": "00:13:a2:00:41:90:79:b1", "original": { "mac": "00:13:a2:00:41:90:79:b1", "receive_options": { "ack": 0, "broadcast": 0, "type": "" }, "data": [ 127, 0, 4, 3, 255, 1, 0, 40, 1, 0, 11, 210, 0, 20, 204, 0, 11, 167, 0, 41, 238, 0, 51, 78, 0, 47, 186, 255, 188, 76, 255, 196, 87, 255, 204, 221, 0, 23 ], "type":

**Comment by zaphod-42** [comment]
Hi David, thanks for letting me know... I've added it to the newest release (1.5.2), please note that time series data is not supported at the moment

**Comment by davidfungf** [comment]
Thank you for your quick response!
