### ISSUE TITLE
XBee nodes?

### ISSUE THREAD

**Issue by MartinSokolov15** [ncd-io/ncd-red-wireless#9]
Hi, can this project be adapted to work for xbee nodes?

**Comment by zaphod-42** [comment]
I'm unsure what you are asking here... are you talking about the existing node-red-contrib-xbee library? Please explain more specifically what you are looking for.

**Comment by martin9115** [comment]
I use Digi Xbee modules and I tried node-red-contrib-xbee library, but i can't obtain wireless sensor data from xbee node. Both Xbee have to be physically connected to PC/RPI, Unlike NCD (ncd-red-wireless ) where only the router have to be physically connected and can obtain wireless sensor data. Also i wish to establish network topology. Is this possible to establish network topology with NCD in NR or in Alfa station software.

**Comment by martin9115** [comment]
I use this xbee modules. Can use them with this node?
https://store.comet.bg/download-file.php?id=14341
https://store.comet.bg/download-file.php?id=13668
